name: Deploy to Firebase

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          
      - run: npm ci
      
      - run: npm run build
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: sozayn-05222025  # Matches .firebaserc config
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}